<?php // ROOT_PATH_WARANAS_LIB + /src/protocol/protocolGlobals.php

const BIN_TERM_SIZE = 32;
const BIN_CONTENT_SIZE = 223;
const BINPACK_RECORD_SIZE = BIN_TERM_SIZE + BIN_CONTENT_SIZE + 1;
const BINPACK_LEVELS = 8;
const BINPACK_LINES = BINPACK_RECORD_SIZE;
const BYTE_STATUS_EMPTY = "\x00";
const BYTE_STATUS_USED = "\x01";
const BIN_LINE_SIZE = BINPACK_LEVELS * BINPACK_RECORD_SIZE;
